### ISSUE TITLE
[SciPy] semantic error: Attribute declaration not supported

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#1092]
```fortran

      subroutine sgetv0 
     &   ( ido, bmat, itry, initv, n, j, v, ldv, resid, rnorm, 
     &     ipntr, workd, ierr )

      include   'debug.h'
      include   'stat.h'
c
c     %------------------%
c     | Scalar Arguments |
c     %------------------%
c
      character  bmat*1
      logical    initv
      integer    ido, ierr, itry, j, ldv, n
      Real
     &           rnorm
c
c     %-----------------%
c     | Array Arguments |
c     %-----------------%
c
      integer    ipntr(3)
      end
```

on executing throws the following error 

```
semantic error: Attribute declaration not supported
  --> /home/pranavchiku/scipy/scipy/sparse/linalg/_eigen/arpack/ARPACK/SRC/sgetv1.f:14:16 - 23:12
   |
14 |          logical    initv
   |                   ^^^^^^^...
...
   |
23 |          integer    ipntr(3)
   | ...^^^^^^^^^^^^ 
```

**Comment by Pranavchiku** [comment]
Okay, so there are quite a lot of these kinds of errors for files in [scipy/sparse/linalg/_eigen/arpack/ARPACK/SRC/](https://github.com/scipy/scipy/tree/main/scipy/sparse/linalg/_eigen/arpack/ARPACK/SRC).

**Comment by Pranavchiku** [comment]
Few cases, 
```
semantic error: Attribute declaration not supported
   --> /home/pranavchiku/scipy/scipy/sparse/linalg/_eigen/arpack/ARPACK/SRC/dnapps.f:158:40 - 166:4
    |
158 |          integer    kev, ldh, ldq, ldv, n, np
    |                                           ^^^...
...
    |
166 |         &           v(ldv,kev+np), q(ldq,kev+np), workd(2*n), workl(kev+np)
    | ...^^^^ 

```
```
semantic error: Attribute declaration not supported
  --> /home/pranavchiku/scipy/scipy/sparse/linalg/_eigen/arpack/ARPACK/SRC/dstats.f:14:23 - 16:16
   |
14 |          include   'stat.h'
   |                          ^^...
...
   |
16 |    c     %-----------------------%
   | ...^^^^^^^^^^^^^^^^ 

```

**Comment by gptsarthak** [comment]
I believe this issue is fixed and can be closed.

**Comment by certik** [comment]
I am still getting the same issue as reported:
```console
$ lfortran --show-asr --fixed-form --implicit-typing --implicit-interface sgetv0.f 
semantic error: Common attribute declaration not supported yet
   --> sgetv0.f:135:16 - 144:12
    |
135 |          logical    initv
    |                   ^^^^^^^...
...
    |
144 |          integer    ipntr(3)
    | ...^^^^^^^^^^^^ 
```
It will get fixed once we implement common blocks, that Pranav is working on.
