### ISSUE TITLE
conda install of mac lfortran 0.31.0 on an m1 does not have debug support

### ISSUE THREAD

**Issue by BlameTroi** [lfortran/lfortran#3190]
from the question on the discourse, I could not compile with -g.

```
Pertinent output:

(lf) troi ~/projects/fortran/quickstart $ lfortran --version
LFortran version: 0.31.0
Platform: macOS ARM
Default target: arm64-apple-darwin23.2.0
(lf) troi ~/projects/fortran/quickstart $ cat hello.f90
program hello
  ! This is a comment line; it is ignored by the compiler
  print *, 'Hello, World!'
end program hello
(lf) troi ~/projects/fortran/quickstart $ lfortran -g hello.f90
semantic error: The `runtime stacktrace` is not enabled. To get the stack traces or debugging information, please re-build LFortran with `-DWITH_RUNTIME_STACKTRACE=yes`
````

**Comment by junghans** [comment]
I guess you could add that option here:
https://github.com/conda-forge/lfortran-feedstock/blob/main/recipe/build.sh

**Comment by certik** [comment]
Yes, put `-DWITH_RUNTIME_STACKTRACE=yes` in here: https://github.com/conda-forge/lfortran-feedstock/blob/908e57b92a02e31fb98def224c978baf115babeb/recipe/build.sh#L52

**Comment by Shaikh-Ubaid** [comment]
Runtime stacktraces are now enabled with lfortran `0.32.0`.

```console
% lfortran --version
LFortran version: 0.32.0
Platform: macOS ARM
Default target: arm64-apple-darwin22.4.0
% which lfortran
/Users/ubaid/conda_root/envs/lf_conda/bin/lfortran
% lfortran -g examples/expr2.f90 
semantic error: The `emit_debug_line_column` is not enabled; please use the `--debug-with-line-column` option to get the correct location information


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

I think this issue is fixed.

**Comment by certik** [comment]
It's not fixed yet. When you use it, you get:
```console
$ lfortran -g --debug-with-line-column  examples/expr2.f90
sh: llvm-dwarfdump: command not found
```
You can install the missing command using `conda install llvmdev`. Then you get this error:
```console
$ lfortran -g --debug-with-line-column  examples/expr2.f90
sh: /Users/ondrej/mambaforge/envs/t10/bin/../include/lfortran/impure/../dwarf_convert.py: No such file or directory
Error in creating the files used to generate the debug information. This might be caused because either `llvm-dwarfdump` or `Python` are not available. Please activate the CONDA environment and compile again.
```

The conda package is missing some files needed for the debugging information.

I do not like using external tools and scripts (`llvm-dwarfdump`, `dwarf_convert.py`) like that, I would like LFortran to have this support natively, but it is not implemented yet. To fix this issue:

* [ ] add `dwarf_convert.py` into conda
* [ ] add a test at https://github.com/lfortran/lfortran-conda-testing/ to test that debugging information works on all platforms

Eventually we'll simplify the dependencies.

**Comment by BlameTroi** [comment]
I installed llvmdev into my conda environment and I still get the missing dwarf_convert.py message. Not sure what else I should install. I'm not really familiar with llvm tooling. here's what i've got in my lf environment:
```
# packages in environment at /Users/troi/miniconda3/envs/lf:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h93a5062_5    conda-forge
ca-certificates           2023.11.17           hf0a4a13_0    conda-forge
cctools                   973.0.1             hf67d63f_15    conda-forge
cctools_osx-arm64         973.0.1             h998149b_15    conda-forge
clang                     17.0.6               haab561b_2    conda-forge
clang-17                  17.0.6          default_hd209bcb_2    conda-forge
clang_impl_osx-arm64      17.0.6               he47c785_8    conda-forge
clang_osx-arm64           17.0.6               h54d7cd3_8    conda-forge
clangxx                   17.0.6          default_h5c94ee4_2    conda-forge
compiler-rt               17.0.6               h3808999_1    conda-forge
compiler-rt_osx-arm64     17.0.6               h3808999_1    conda-forge
configargparse            1.7                pyhd8ed1ab_0    conda-forge
fortls                    2.13.0          py312h81bd7bf_2    conda-forge
fpm                       0.10.0               hf7316ee_0    conda-forge
fprettify                 0.3.7              pyhd8ed1ab_0    conda-forge
gfortran                  13.2.0               h1ca8e4b_1    conda-forge
gfortran_impl_osx-arm64   13.2.0               h252ada1_2    conda-forge
gfortran_osx-arm64        13.2.0               h57527a5_1    conda-forge
gmp                       6.3.0                h965bd2d_0    conda-forge
icu                       73.2                 hc8870d7_0    conda-forge
isl                       0.26            imath32_h347afa1_101    conda-forge
json5                     0.9.14             pyhd8ed1ab_0    conda-forge
ld64                      609                 h39a299f_15    conda-forge
ld64_osx-arm64            609                 h6a44367_15    conda-forge
lfortran                  0.32.0               hbeb2e11_0    conda-forge
libclang-cpp17            17.0.6          default_hd209bcb_2    conda-forge
libcxx                    16.0.6               h4653b0c_0    conda-forge
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           13_2_0_hd922786_2    conda-forge
libgfortran-devel_osx-arm64 13.2.0               h5d7a38c_2    conda-forge
libgfortran5              13.2.0               hf226fd6_2    conda-forge
libiconv                  1.17                 h0d3ecfb_2    conda-forge
libllvm17                 17.0.6               haab561b_1    conda-forge
libsodium                 1.0.18               h27ca646_1    conda-forge
libsqlite                 3.44.2               h091b4b1_0    conda-forge
libxml2                   2.12.4               h0d0cfa8_1    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
llvm-openmp               17.0.6               hcd81f8e_0    conda-forge
llvm-tools                17.0.6               haab561b_1    conda-forge
llvmdev                   17.0.6               haab561b_1    conda-forge
mpc                       1.3.1                h91ba8db_0    conda-forge
mpfr                      4.2.1                h9546428_0    conda-forge
ncurses                   6.4                  h463b476_2    conda-forge
openssl                   3.2.0                h0d3ecfb_1    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
python                    3.12.1          hdf0ec26_1_cpython    conda-forge
python_abi                3.12                    4_cp312    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
sigtool                   0.1.3                h44b9a77_0    conda-forge
tapi                      1100.0.11            he4954df_0    conda-forge
tk                        8.6.13               h5083fa2_1    conda-forge
tzdata                    2023d                h0c530f3_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xeus                      3.0.5                hffc8910_1    conda-forge
xeus-zmq                  1.0.3                h54398fd_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
zeromq                    4.3.5                h965bd2d_0    conda-forge
zlib                      1.2.13               h53f4e23_5    conda-forge
zstd                      1.5.5                h4f39d0f_0    conda-forge
```

**Comment by certik** [comment]
The runtime debugging information is unfortunately not super user friendly yet. If anyone has time to help us clean it up, we would really appreciate it. Otherwise we'll get to it once we reach beta.

**Comment by Shaikh-Ubaid** [comment]
I think this issue is fixed with the latest `lfortran` `v0.33.0`. @BlameTroi could you try it on your system and share if it works for you? You need lfortran `v0.33.0` and you also need `llvmdev` `11.1.0`. Thanks for reporting the issue.

**Comment by BlameTroi** [comment]
Yep, worked fine. llvmdev 12.0.0 was already installed.

Thanks all!

**Comment by Shaikh-Ubaid** [comment]
>Yep, worked fine. llvmdev 12.0.0 was already installed.

Great! Thanks for reporting the issue!
