### ISSUE TITLE
transfer string to character array: bug

### ISSUE THREAD

**Issue by harperjf** [lfortran/lfortran#7049]
Issue #6109 revealed a bug in transfer(array,string). The program below reveals a bug in the opposite transfer, of a string to a character array.
```
  print "(3(1X,A))",transfer('abc',['x'])
end program
```
Output from gfortran, g95, ifx, or AMD flang
```
 a b c
```
Output from lfortran 0.51.0
```
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc 
Segmentation fault (core dumped)
```

**Comment by Pranavchiku** [comment]
This works with latest main:

```console
% cat a.f90 
  print "(3(1X,A))",transfer('abc',['x'])
end program
% lfortran a.f90 
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc abc abc
 abc 
% echo $?
0
```

**Comment by harperjf** [comment]
The program may "work" in the sense that it's not doing a segfault but 
its output is still very wrong: it should have been the one line
```
  a b c
``` 
as you'll see if you also try another compiler.

On Fri, 2 May 2025, Pranav wrote:

> Date: Fri, 2 May 2025 06:12:08 +0000
> From: Pranav ***@***.***>
> Reply-To: lfortran/lfortran
>     ***@***.***>
> To: lfortran/lfortran ***@***.***>
> Cc: harperjf ***@***.***>, Author ***@***.***>
> Subject: Re: [lfortran/lfortran] transfer string to character array: bug
>     (Issue #7049)
> 
> Pranavchiku left a comment (lfortran/lfortran#7049)
>
> This works with latest main:
>
> ```console
> % cat a.f90
>  print "(3(1X,A))",transfer('abc',['x'])
> end program
> % lfortran a.f90
> abc abc abc
> abc abc abc
> abc abc abc
> abc abc abc
> abc abc abc
> abc abc abc
> abc abc abc
> abc abc abc
> abc abc abc
> abc abc abc
> abc abc abc
> abc abc abc
> abc abc abc
> abc abc abc
> abc abc abc
> abc abc abc
> abc abc abc
> abc abc abc
> abc abc abc
> abc abc abc
> abc abc abc
> abc
> % echo $?
> 0
> ```
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/lfortran/lfortran/issues/7049#issuecomment-2846447222
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>
>


-- John Harper, School of Mathematics and Statistics
Victoria Univ. of Wellington, PO Box 600, Wellington 6140, New Zealand.
e-mail ***@***.***

**Comment by Pranavchiku** [comment]
Yes, we have to fix that. Segfault was fixed in one of the recent PRs and due to divergence in output I didn't close this issue.

**Comment by harperjf** [comment]
With lfortran 0.57.0 the output is different but still wrong: 22 lines of blanks.

**Comment by HarshitaKalani** [comment]
This now works perfectly. To close this let's add a test.
```console
% gfortran a.f90 && ./a.out
 a b c
% lfortran a.f90
 a b c
```

**Comment by harperjf** [comment]
Good!

On Sun, 25 Jan 2026, Harshita Kalani wrote:

> Date: Sun, 25 Jan 2026 08:39:44 +0000
> From: Harshita Kalani ***@***.***>
> Reply-To: lfortran/lfortran
>     ***@***.***>
> To: lfortran/lfortran ***@***.***>
> Cc: harperjf ***@***.***>, Author ***@***.***>
> Subject: Re: [lfortran/lfortran] transfer string to character array: bug
>     (Issue #7049)
> 
> HarshitaKalani left a comment (lfortran/lfortran#7049)
>
> This now works perfectly. To close this let's add a test.
> ```console
> % gfortran a.f90 && ./a.out
> a b c
> % lfortran a.f90
> a b c
> ```
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/lfortran/lfortran/issues/7049#issuecomment-3796208003
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>
>


-- John Harper, School of Mathematics and Statistics
Victoria Univ. of Wellington, PO Box 600, Wellington 6140, New Zealand.
e-mail ***@***.***
